 # TODO: change this id value for each drone, need to change also id in worker.launch
nodeID: 1                      
nodeType: "mocap client"
ballRealSizeInMeter: 0.144      
XsensorSizeInMillimeter: 1354.724121
YsensorSizeInMillimeter: 10

# Use the options below only for stationary beacons
node_pos_x: 0.0
node_pos_y: 0.0
node_pos_z: 0.0
node_ori_roll: 0.0
node_ori_pitch: 0.0
node_ori_yaw: 0.0