nodeID: 1                    # TODO: change this id value for each drone, need to change also id on worker.launch
nodeType: "mocap client"
ballRealSizeInMeter: 0.144     # 0.06977 : baseball ball | 0.03942 : purple ping pong ball  | 0.24 Google ball |  0.208 Purple scoccer ball | 0.144 yelllow big tennis ball
XsensorSizeInMillimeter: 1354.724121 # 2959.689209
YsensorSizeInMillimeter: 10

# Use the options below only for stationary beacons
node_pos_x: 0.0
node_pos_y: 0.0
node_pos_z: 0.0
node_ori_roll: 0.0
node_ori_pitch: 0.0
node_ori_yaw: 0.0